DROP TABLE IF EXISTS CERTIFICATI_MEDICI;
DROP TABLE IF EXISTS ISCRIZIONI_STAGIONALI;
DROP TABLE IF EXISTS GIOCATORI;
DROP TABLE IF EXISTS UTENTI_CATEGORIE;
DROP TABLE IF EXISTS CATEGORIE;
DROP TABLE IF EXISTS UTENTI_SOCIETA;
DROP TABLE IF EXISTS SOCIETA;
DROP TABLE IF EXISTS UTENTI;

CREATE TABLE UTENTI (
    id_utente BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cognome VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    codice_fiscale CHAR(16) UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE SOCIETA (
    id_societa BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    partita_iva VARCHAR(50) UNIQUE
);

CREATE TABLE UTENTI_SOCIETA (
    id_utente BIGINT NOT NULL,
    id_societa BIGINT NOT NULL,
    ruolo ENUM('ADMIN', 'VIEWER') NOT NULL,
    PRIMARY KEY (id_utente, id_societa),
    FOREIGN KEY (id_utente) REFERENCES UTENTI(id_utente) ON DELETE CASCADE,
    FOREIGN KEY (id_societa) REFERENCES SOCIETA(id_societa) ON DELETE CASCADE
);

CREATE TABLE CATEGORIE (
    id_categoria BIGINT AUTO_INCREMENT PRIMARY KEY,
    id_societa BIGINT NOT NULL,
    nome_categoria VARCHAR(50) NOT NULL,
    FOREIGN KEY (id_societa) REFERENCES SOCIETA(id_societa) ON DELETE CASCADE
);

CREATE TABLE UTENTI_CATEGORIE (
    id_utente BIGINT NOT NULL,
    id_categoria BIGINT NOT NULL,
    PRIMARY KEY (id_utente, id_categoria),
    FOREIGN KEY (id_utente) REFERENCES UTENTI(id_utente) ON DELETE CASCADE,
    FOREIGN KEY (id_categoria) REFERENCES CATEGORIE(id_categoria) ON DELETE CASCADE
);

CREATE TABLE GIOCATORI (
    id_giocatore BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cognome VARCHAR(100) NOT NULL,
    data_nascita DATE NOT NULL,
    codice_fiscale CHAR(16) UNIQUE,
    sesso ENUM('M','F') NOT NULL
);

CREATE TABLE ISCRIZIONI_STAGIONALI (
    id_iscrizione BIGINT AUTO_INCREMENT PRIMARY KEY,
    id_giocatore BIGINT NOT NULL,
    id_categoria BIGINT NOT NULL,
    stagione VARCHAR(9) NOT NULL,
    UNIQUE (id_giocatore, id_categoria, stagione),
    FOREIGN KEY (id_giocatore) REFERENCES GIOCATORI(id_giocatore) ON DELETE CASCADE,
    FOREIGN KEY (id_categoria) REFERENCES CATEGORIE(id_categoria) ON DELETE CASCADE
);

CREATE TABLE CERTIFICATI_MEDICI (
    id_certificato BIGINT AUTO_INCREMENT PRIMARY KEY,
    id_giocatore BIGINT NOT NULL,
    data_inserimento DATE NOT NULL,
    data_scadenza DATE NOT NULL,
    FOREIGN KEY (id_giocatore) REFERENCES GIOCATORI(id_giocatore) ON DELETE CASCADE
);